site_name: BioCloud HPC user guide
site_description: 'User guide for the BioCloud HPC at the section of Biotechnology at Aalborg University'
site_author: 'Kasper Skytte Andersen'
docs_dir: docs/
repo_name: 'cmc-aau/biocloud-docs'
repo_url: 'https://github.com/cmc-aau/biocloud-docs'
nav:
  - index.md
  - access.md
  - Ressource management:
    - slurm/intro.md
    - slurm/request.md
    - slurm/jobcontrol.md
    - slurm/accounting.md
    - slurm/other.md
  - Software:
    - software/modules.md
    - software/conda.md
    - software/containers.md
  - storage.md
  - events.md
theme:
  name: material
  palette: 
    scheme: slate
  features:
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details