site_name: BioCloud HPC user guide
site_description: 'User guide for the BioCloud HPC at the section of Biotechnology at Aalborg University'
site_author: 'Kasper Skytte Andersen'
docs_dir: docs/
repo_name: 'cmc-aau/biocloud-docs'
repo_url: 'https://github.com/cmc-aau/biocloud-docs'
nav:
  - index.md
  - Access:
    - access/ssh.md
    - access/webportal.md
  - Resource management:
    - slurm/intro.md
    - slurm/jobsubmission.md
    - slurm/partitions.md
    - slurm/efficiency.md
    - slurm/accounting.md
    - slurm/jobcontrol.md
    - slurm/other.md
  - Software:
    - software/conda.md
    - software/containers.md
    - software/modules.md
    #- software/preinstalled.md
  - Guides:
    - Interactive Web portal (OpenOndemand):
      - guides/webportal/files.md
      - guides/webportal/jobqueue.md
      #- guides/webportal/jobcomposer.md
      - guides/webportal/shell.md
      - Interactive apps:
        - guides/webportal/apps/virtualdesktop.md
        - guides/webportal/apps/jupyter.md
        - guides/webportal/apps/rstudio.md
        - guides/webportal/apps/coder.md
    - Snakemake:
      - guides/snakemake/intro.md
      - guides/snakemake/tutorial.md
      - guides/snakemake/biocloud.md
    - guides/sshdslurm.md
  - storage.md
theme:
  name: material
  palette: 
    scheme: slate
  features:
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details